config/routes.rb
Rails.application.routes.draw do

  match '/recipes/get_random_recipe', {:via => :get, :to => 'recipes#get_random_recipe'}

  devise_for :users
  match '/tags/search', {:via => :get, :to => 'tags#search'}
  resources :tags

  match '/ratings', {:via => :get, :to => 'ratings#index'}
  resources :ratings

  match '/', :via => [:get], :to => redirect('/home.html')

  match('/recipes/:id/add_tag', {:via => :post, :to => 'recipes#add_tag'})

  match('/recipes/:id/add_rating', {:via => :post, :to => 'recipes#add_rating'})
  resources :recipes

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :title, :presence => true
  validates :ingredients, :presence => true
  validates :instructions, :presence => true

  has_many :tags, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  has_attached_file :image, styles: {small: "60x60#", med: "300x300#", large: "500x500#"}
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  # validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:stars, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, except:  [:index, :show, :get_random_recipe]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @tags = Tag.all
    @recipe = Recipe.new
    @ratings = Rating.all
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @ingredients = Recipe.new(params[:ingredients])
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_tag
    @recipe = Recipe.find(params[:id])
    newTag = Tag.new(params[:tag])
    if newTag.valid?
      newTag.save
      @recipe.tags << newTag
      @recipe.save
    render 'show.html.erb'
  end
  end

  def add_rating
    @recipe = Recipe.find(params[:id])
    newRating = Rating.new(params[:rating])
    if newRating.valid?
      newRating.save
      @recipe.ratings << newRating
      @recipe.save
    end
  render 'show.html.erb'
  end

  def get_random_recipe
     @recipe = Recipe.all.sample
     respond_to do |format|
     format.json { render :show, status: :ok, location: @recipe }
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :author, :ingredients, :instructions, :image)
    end
  end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  #search
  def search
    if !params[:search_string].nil?
    search_string = params[:search_string].strip
    @tags = Tag.where(:name => search_string)
  end
end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>


  <!-- <div id="user_nav"> -->
     <!-- <% if user_signed_in? %>
       Logged in as <strong><%= current_user.email %></strong>
       <%= link_to 'Edit Profile', edit_user_registration_path %> |
       <%= link_to "Logout", destroy_user_session_path, method: :delete %>
     <% else %>
       <%= link_to "Sign Up", new_user_registration_path %> |
       <%= link_to "Login", new_user_session_path %>
     <% end %> -->
   <!-- </div> -->

<%= yield %>

<br></br>
<br></br>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-11">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</body>
</html>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.number_field :recipe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.stars %></td>
        <td><%= rating.recipe.title %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @rating.stars %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @rating.recipe_id %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { multipart: true} do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <span class="input"><%= f.text_field :title %></span>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <span class="input"><%= f.text_field :author %></span>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <span class="input"><%= f.text_area :ingredients %></span>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <span class="input"><%= f.text_area :instructions %></span>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <span class="input"><%= f.file_field :image %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>Editing Recipe</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @recipe %> |
    <%= link_to 'Back', recipes_path %>
  </div>
  <div class="col-md-2">
  </div>

</div>

app/views/recipes/index.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>Listing Recipes</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Rating</th>

          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <td><%= recipe.title %></td>
            <td><%= recipe.author %></td>
            <td><% if !recipe.ratings.empty? %>
              <%= recipe.ratings.average(:stars).round(1) %>
              </td>
            <% end %>

            <!-- <td><%= recipe.ingredients %></td>
            <td><%= recipe.instructions %></td> -->
            <td><%= link_to 'Show', recipe %></td>
            <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
            <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Recipe', new_recipe_path %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/recipes/new.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
    <h1>New Recipe</h1>

    <%= render 'form' %>

    <%= link_to 'Back', recipes_path %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/recipes/show.html.erb
<%= render('header') %>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8 main">
          <div class="row">
            <div class="col-md-6">
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Title:</strong>
              <%= @recipe.title %>
            </p>

            <p>
              <strong>Author:</strong>
              <%= @recipe.author %>
            </p>

            <p>
              <strong>Ingredients:</strong>
              <%= @recipe.ingredients %>
            </p>

            <p>
              <strong>Instructions:</strong>
              <%= @recipe.instructions %>
            </p>

            <p>
              <strong>Tags:</strong>
              <% @recipe.tags.each do |tag| %>
              <%= tag.name %>,
              <% end %>
            </p>


            <p>
              <strong>Average Rating:</strong>
              <% if !@recipe.ratings.average(:stars).nil? %>
                <%= @recipe.ratings.average(:stars).round(1) %>
                <% end %>
            </p>

            <form action="/recipes/<%=@recipe.id%>/add_tag" method="post">
              <div class="field">
                <label for="tag_name">Tag Name</label><br>
                <input type="text" name="tag[name]" id="tag_name" />
              </div>
              <div class="actions">
                <input type="submit" name="commit" value="Add Tag" />
              </div>
            </form>

            <form action="/recipes/<%=@recipe.id%>/add_rating" method="post">
                <label for="star_rating">Rating</label><br>
                <select  class="input" name="rating[stars]" id="star_rating">
                  <option class="rate">Rate Me</option>
                  <option value="1">1 Star</option>
                  <option value="2">2 Stars</option>
                  <option value="3">3 Stars</option>
                  <option value="4">4 Stars</option>
                  <option value="5">5 Stars</option>
                </select>
              <div class="actions"><br>
                <input type="submit" name="commit" value="Rate" />
              </div>
            </form>

            <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
            <%= link_to 'Back', recipes_path %>
          </div>
          <div class="col-md-6 foodpic">
            <%= image_tag @recipe.image.url(:med) %>
          </div>
        </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <span class="input"><%= f.text_field :name %></span>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<%= render('header') %>
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<%= render('header') %>
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<%= render('header') %>
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/search.html.erb
<%= render('header') %>

<div class="row">
  <div class="col-md-2">
  </div>

  <div class="col-md-8 main">


    <h2>Search for Recipes by Tag</h2>

    <form action="/tags/search" method="get">
      <label for="search_by_tag">Tag Name:</label>
      <input id="search_by_tag" type="text" name="search_string"/>
      <input type="submit" value="Search"/>
    <form>

    <% if !@tags.nil? %>
      <% if !@tags.empty? %>
        <h3>Recipes Found</h3>
          <% @tags.each do |tag| %>
            <%= link_to(tag.recipe.title, tag.recipe) %><br>
          <% end %>
          <% else %>
        <h3>No Recipes Found :(</h3>
      <% end %>
    <% end %>

  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/tags/show.html.erb
<%= render('header') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>